---
- hosts: webservers
  become: yes
  become_method: sudo
  tasks:
    - name: Instalar Php complemntos
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'php7.2-common','php7.2-cli','php7.2-gd','php7.2-mysql','php7.2-curl','php7.2-intl','php7.2-mbstring','php7.2-bcmath','php7.2-imap','php7.2-xml','php7.2-zip' ]