---
- hosts: webservers
  # connection: local
  become: yes
  become_method: sudo
  tasks:
    # This playbook sets up whole stack.
     
    - name: Configurations to "vagrant" host
      hosts: vagrant
      remote_user: root
      become: yes
     
      vars:
        installer: /tmp/installer.php
     
      tasks:
        # sudo apt-get install php-cli
        - name: Install php-cli
          apt:
            name: php-cli
            state: present
          tags:
            - composer
     
        # curl -sSk https://getcomposer.org/installer -o /tmp/composer-installer.php
        - name: Download composer
          get_url:
            url: https://getcomposer.org/installer
            dest: "{{ installer }}"
          tags:
            - composer
     
        # php /tmp/composer-installer.php
        # sudo mv composer.phar /usr/local/bin/composer
        - name: Install composer
          command: "{{ item }}"
          with_items:
            - "php {{ installer }}"
            - mv composer.phar /usr/local/bin/composer
          tags:
            - composer
     
        # sudo rm /tmp/composer-installer.php
        - name: Remove composer installer
          file:
            path: "{{ installer }}"
            state: absent
          tags:
            - composer
     
        - name: Print composer version
          command: composer -v
          register: version
        - debug: msg="{{ version.stdout_lines }}"